name: Numpy and Pandas Assignment Autograder

on:
  push:
  pull_request:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas pytest pytest-json-report

    - name: Run Tests
      run: pytest tests.py
      continue-on-error: true  # Ensures the workflow runs even if tests fail

    - name: Generate Report
      run: pytest tests.py --json-report

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: .report.json
